### ISSUE TITLE
Quests status

### ISSUE THREAD

**Issue by dmorcellet** [LotroCompanion/lotro-companion#106]
From SnerkDevil:
As a quest completionist, I would like to see a completed checkbox for the quests, just like for the deeds.

**Comment by cyberox** [comment]
This could be a great addition, as Wintersong of Arda (LotRO Character Log) will be closed end of April 2021.

**Comment by dmorcellet** [comment]
Good news is that quests status could be imported from the client memory, as for deeds.

**Comment by cyberox** [comment]
omg, never expected that! I can't wait to test out this feature. 😉

**Comment by dmorcellet** [comment]
Feature implemented.
Still TODO:
- display the completion count for repeatable quests: in the table (and in the form?)
- better centering of the map associated to a quest/deed status (relative to parent window)

**Comment by dmorcellet** [comment]
Done.
