### ISSUE TITLE
See if we could ease items search by ignoring accents

### ISSUE THREAD

**Issue by dmorcellet** [LotroCompanion/lotro-companion#4]
(such as in Anórien)

**Comment by dmorcellet** [comment]
Use this search everywhere in the app (filters: deeds, quests...).

**Comment by sgronlun** [comment]
I think I can give this a go. Maybe `delta.games.lotro.utils` is a good location for such a feature?

**Comment by sgronlun** [comment]
A fix is waiting to be merged in https://github.com/dmorcellet/delta-common/pull/2

**Comment by sgronlun** [comment]
The previous fix has a bug. Most likely it is due to "ignore-case" and the normalized string is not ignore-case. I will fix that.

**Comment by sgronlun** [comment]
Fixed by https://github.com/dmorcellet/delta-common/commit/fc67a6384b63aa0dd73dc9a2e343a00d817bbdd7

**Comment by dmorcellet** [comment]
Applied the fix everywhere.
