### ISSUE TITLE
Import: Cannot ghet client data

### ISSUE THREAD

**Issue by olilau** [LotroCompanion/lotro-companion#451]
Hi,

I'm using version 20.7.
Recently, I cannot import character data. I'm getting an error: Cannot get client data
I've tried when already in the world and from the character choice panel.

Thanks.

**Comment by sgronlun** [comment]
> I'm using version 20.7. Recently, I cannot import character data. I'm getting an error: Cannot get client data I've tried when already in the world and from the character choice panel.

The most recent update of Lotro broke LC's import function. I know LC (the person) is travelling but expect an update soon-ish.

**Comment by dmorcellet** [comment]
Pointers updated in lotro-memory.
It will be fixed in the incoming release, "soon".

**Comment by olilau** [comment]
Thank you :)
