### ISSUE TITLE
Investigate the status of 2 quests

### ISSUE THREAD

**Issue by dmorcellet** [LotroCompanion/lotro-companion#455]
Zimoon said:
It's a bit odd that getting quests "Unguarded Treasure" and "Instructions in the Map" is either-one-or-the-other in-game but that is not indicated in the XML file. I wonder what governs that fact then? In-game I mean, and I've noticed it with multiple toons

**Comment by dmorcellet** [comment]
Cannot find out the source of the behavior of these 2 classes.

**Comment by sgronlun** [comment]
Should we hard-code this as a work-around? How do you usually do?

**Comment by dmorcellet** [comment]
Never hit such a case.
If we had to hard-code something, it would be in the data generation tools, so that the runtime code stays uncluttered.
