### ISSUE TITLE
Show coords for "named" mobs

### ISSUE THREAD

**Issue by sgronlun** [LotroCompanion/lotro-companion#505]
It would be nice to show coords for "named" mobs. But since all items/beings in Lotro have "names" I guess it would rather be a request to display coords for `mobs >= <some difficulty level>`, such as Elite or whatever is available and reasonable to filter on.

**Comment by dmorcellet** [comment]
Monster difficulty level is not accessible. Only mob DID, name, genus/species/subspecies and position(s).

**Comment by sgronlun** [comment]
Close this then

**Comment by dmorcellet** [comment]
The new feature in LC 21 about display selection on maps should bring some possibilites for this.
Now, one can filter on named mobs, and have a table that shows their position(s).
