### ISSUE TITLE
Add feature to filter on monster name to maps

### ISSUE THREAD

**Issue by sgronlun** [LotroCompanion/lotro-companion#506]
Looking at e.g. map of Angmar for e.g. Durbskút involves a lot of mouse hovering to find where he could possibly spawn. Some such mobs spawn at just one location while others have many possible spawn-points. If having "monsters" enabled in the filter it would be nice to be able to filter on a name, or just part of a name.

**Comment by dmorcellet** [comment]
You can already filter of "mob" and on "name part" using the current filtering system.
There are plans for fine-grained filtering.

**Comment by sgronlun** [comment]
I had missed out on this feature but now I have found it. Nice. Closing.

**Comment by dmorcellet** [comment]
Fine grained filtering will be available in the next release.
