### ISSUE TITLE
Add "Requires Monsterplay" and "Requires Glory Rank X"

### ISSUE THREAD

**Issue by xDaavos** [LotroCompanion/lotro-companion#540]
There are items that you can only equip when you are in the Ettenmoors. Currently the data does not contain such connected informations.

As an example: 
```<item key="1879423552" name="Reinforced Absorbing Stud of the Ruthless">```

You both need Glory Rank 3 and you also must be in the Ettenmoors. See also https://lotro-wiki.com/index.php/Item%3AFierce_Ring_of_the_Spirited_Relentless

**Comment by dmorcellet** [comment]
Added glory rank requirements.

**Comment by dmorcellet** [comment]
Done!

**Comment by xDaavos** [comment]
Thank you!
