### ISSUE TITLE
Can't save character gear

### ISSUE THREAD

**Issue by RedDust99** [LotroCompanion/lotro-companion#553]
Hello, I've tried searching through closed issues, did not see anything in the documentation.  I successfully imported all my characters by logging in to each one, but none of them have any gear or virtues.  Figured I'd follow the instructions to just do it manually by choosing.  When I click ok and leave the window with the character gear, nothing saves.

Sorry I don't use Discord, so hopefully someone will let me know what I'm doing wrong here - thanks!

**Comment by dmorcellet** [comment]
Hi @RedDust99. Please send the log files at lotrocompanion@gmail.com.
The log files are found in c:\users\YOU\.lotrocompanion\data\logs.
Usually 1 file per day. Send the one of the day where it fails.

**Comment by dmorcellet** [comment]
@RedDust99 What's your status now?

**Comment by dmorcellet** [comment]
Closing...
