### ISSUE TITLE
LC_SHOW_TECHNICAL_COLUMNS failing if set to True

### ISSUE THREAD

**Issue by dt192** [LotroCompanion/lotro-companion#586]
This should probably use `equalsIgnoreCase` as it fails if the user sets it to `True` or `TRUE`

https://github.com/LotroCompanion/lotro-companion/blob/30bd3657b3965f632e7c69e13b87edba5eefeda5/src/main/java/delta/games/lotro/gui/utils/UiConfiguration.java#L16C4-L16C31

**Comment by dmorcellet** [comment]
Fixed.
