### ISSUE TITLE
Quests filter: add support for profession requirement

### ISSUE THREAD

**Issue by dmorcellet** [LotroCompanion/lotro-companion#592]
- in the quests explorer, add a "profession" requirement, besides "race" and "class".
- in the quests status, if the current character has some professions, then filter out the profession he does not have.

From Discord, Zimoon, 7/2/2024:
It seems "requirements" is not any select-able column on the Quest Status window --- it would be nice to have that as some quests are unavailable for certain professions or races.
This is from looking up Bree-spear -- Introduction on my Burglar/Scholar account

**Comment by dmorcellet** [comment]
The quests used in the quests status are already filtered using the charcacter's class and race.

**Comment by dmorcellet** [comment]
Added a column to show crafting requirements in the items tables and in the deeds/quests tables.

**Comment by dmorcellet** [comment]
Still TODO: filter quests status using current crafting status

**Comment by dmorcellet** [comment]
Added an automatic filter on crafting requirements in the quests/deeds status window.
TODO : in the quests UI, add a filter on profession, next to the race and class filters.

**Comment by dmorcellet** [comment]
Done.

**Comment by sgronlun** [comment]
Great, thanks, looking forward to next release :)
