### ISSUE TITLE
Cardolan map - Filtering for "penthul" does not work ...

### ISSUE THREAD

**Issue by sgronlun** [LotroCompanion/lotro-companion#597]
In Cardolan there is a creature named Penthúl and filtering for "penthul" on the Cardolan map should work with the "ignore exotic character"-fix I provided quite a while ago. But it does not. Filtering for "penth" works though. I have not looked at the source code but just wanted to file this so we don't forget about it.

**Comment by dmorcellet** [comment]
Yes, the fix submission was not integrated (yet...).

**Comment by dmorcellet** [comment]
Done.
