### ISSUE TITLE
damage and dps values for crafted critted items are different in-game

### ISSUE THREAD

**Issue by Sagarmatha-8848** [LotroCompanion/lotro-companion#599]
The dps and damage values for the crit version of crafted weapons are not the same as non-crit but LC shows the same values for both items. 
<img width="534" alt="LC_Forged_Cutlass_il514" src="https://github.com/LotroCompanion/lotro-companion/assets/117691981/ac5f3b18-1898-492c-84f3-d7dfa6dcab90">
<img width="443" alt="crafted_weapons_dps_diff" src="https://github.com/LotroCompanion/lotro-companion/assets/117691981/085b3e6e-1f6c-4dd2-9e74-bc16081ee0b9">

**Comment by dmorcellet** [comment]
Found out why. The effective item level was not used to compute the DPS and the min/max damage value.
There is another problem: in LC, the stats are computed using the item level, while the game uses 'item level+1'... Don't know why.

**Comment by dmorcellet** [comment]
Oh. I see why: itemLevelOffset="1" is not used here.

**Comment by dmorcellet** [comment]
Fixed.
