### ISSUE TITLE
TraitTree, TraitTreeProgression are wrong on several classes for the third TraitTree branch

### ISSUE THREAD

**Issue by MaxThlon** [LotroCompanion/lotro-companion#605]
For what i have see, for minstrel it's the case.
It's the champion's third TraitTreeProgression present not the corresponding class one.
It's for minstrel and guardian for what i've seen, 
Looking inside traittrees.xml search for 
`<step nbPoints="5" traitId="1879273464" traitName="Ardour"/>`
it's used for several classes..

I did look at the xml & dat loading, but nothing seems wrong so my assumption is a fallback value inside 
TraitTreesDataLoader 
[line 90]  PropertiesSet progressionProperties=_facade.loadProperties(progressionId+DATConstants.DBPROPERTIES_OFFSET);
But... well i cant help on this one, i don't have sources files.
Certainly due to classes rework with new yellow trait trees ...

**Comment by dmorcellet** [comment]
I don't understand the issue. May be a mismatch between some trait trees in game and in the XML files/in LC?
WIll have a look later (no access to the game client right now).

**Comment by dmorcellet** [comment]
@MaxThlon Tu peux me contacter à l'adresse qui est dans la fenêtre About de LC.

**Comment by dmorcellet** [comment]
OK. I had a look. Tell me is I'm correct : I found that 4 classes (Warden, Minstrel, Guardian and Brawler) have their yellow spec disabled (even if the yellow traits are still enabled in red and blue).
I searched in the data, but could not find how it is specified in the DAT files. May be it is a UI only thing.
Is that the issue you raised, or did I find something else?

**Comment by MaxThlon** [comment]
Sorry i found this while debugging in some of the java tests,
But if you look at a trait tree inside Lotro companion for a minstrel the yello trait tree advancement
(the vertical bar on the left) 
![minstrel](https://github.com/LotroCompanion/lotro-companion/assets/3929535/ad4012b3-9063-4fee-aebb-16d06817f3d5)
it's the champion (advancement) skills.
The first you see is ardour: `<step nbPoints="5" traitId="1879273464" traitName="Ardour"/>`
if you search inside `LotRO Companion\app\data\lore\traitTrees.xml`
this line is present 5 times, 1 for champ and the others are wrong..

**Comment by dmorcellet** [comment]
Added a "enabled" flag on trait tree branches. It is set to false for the 4 yellow branches that cannot be used as a main branch.
