### ISSUE TITLE
Investigate plural names for items

### ISSUE THREAD

**Issue by dmorcellet** [LotroCompanion/lotro-companion#609]

**Comment by Valardir** [comment]
Defined in the Dat-Files by:
```
Name: Sunstone Shard[e]
PluralName: Sunstone Shards[ps]
```

**Comment by dmorcellet** [comment]
Thanks. That will add 40k lines and 2.5MB to each items.xml label file (+20%).
Definitively worth it.

**Comment by dmorcellet** [comment]
Added plural names in items.xml and related labels files.
