### ISSUE TITLE
Deed "The Adventures of Floid and Dewitt" shows odd name & map for Evendim

### ISSUE THREAD

**Issue by sgronlun** [LotroCompanion/lotro-companion#614]
I select a character --> Deeds --> Category = Race & Social --> Scroll to "The Adventures of Floid and Dewitt" and double click it --> click "Map".

There will be an entry (the last one in my view) named "Landscape", clicking it will display a close-up of the southern tip of the the island where Dewitt and Floid are found.

Nothing says that is a zoom-in on an island in Evendim, but from deducing this entrance to the view just before clicking "Map" one can conclude this must be the Evendim location.

I think the entry should be named "Evendim" instead of "Landscape". And the displayed map should be possible to zoom out.

Many thanks for an otherwise splendid application ;-)
Zimoon

**Comment by dmorcellet** [comment]
We are currently relying on the path: position->landblock->area->map. It seems this path cannot always be trusted and sometimes does not yield the right map.
Studying another way to find out the maps to use for raw positions.

**Comment by dmorcellet** [comment]
Improved the maps finder.
