### ISSUE TITLE
Global Search for Item on Characters?

### ISSUE THREAD

**Issue by Xruptor** [LotroCompanion/lotro-companion#633]
Is there any way to search all my characters to see whom has a particular item and where it's located?  Example, lets say I want to search for "Ancient Iron".  It would search the vaults, shared, and what not of all the characters and display a list of those whom have "Ancient Iron" and what slots they are located in.

I'm not sure if this is a current feature of the addon, but it would be totally useful to track stuff I think :)

**Comment by dmorcellet** [comment]
Hi. This is already available, for all the character of a given account/server.
From the main window, go the Account tab, then choose/open your account.
Then go the the server tab. You'll get a list of your character on this account & server.
Click on the Storage button. It will bring a window similar to the one you get from the character window, but this one will include all the character of the chosen account/server.
In this last window, you can search for items, see where they are, filter on locations, have statistics, and you even get the "same cosmetics" features that will let you know if you have several items which look the same.
Enjoy.
Feel free to ask for more, or say it is more than enough!

**Comment by Xruptor** [comment]
This is more than enough!  Sorry, I didn't realize you can double click on the Account tab to bring this up.  I wish there was a help menu or something that at least went over things briefly.  I know there is a wiki manual but it's a bit cumbersome to go through. Thank you for such a wonderful program!  This is truly a fantastic piece of software and it's much appreciated.  💚
